In [39]:
import pandas as pd
import numpy as np

Reading CSV

In [40]:
df = pd.read_csv("Football.csv")
df.head()

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016

In [41]:
#From Link
# link = 'https://raw.githubusercontent.com/AshishJangra27/Data-Analysis-with-Python-GFG/main/3.%20Data%20Preprocessing%20-%20Removing%20Null%20Value%20Rows/googleplaystore.csv'
# df = pd.read_csv(link)
# df.head()

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  660 non-null    object
 1   League                   660 non-null    object
 2   Club                     626 non-null    object
 3   Player Names             660 non-null    object
 4   Matches_Played           660 non-null    int64
 5   Substitution             660 non-null    int64
 6   Mins                     660 non-null    int64
 7   Goals                    660 non-null    int64
 8   xG                       660 non-null    float64
 9   xG Per Avg Match         660 non-null    float64
 10  Shots                    660 non-null    int64
 11  OnTarget                 660 non-null    int64
 12  Shots Per Avg Match      660 non-null    float64
 13  On Target Per Avg Match  660 non-null    float64
 14  Year                     660 non-null    int64
dtypes: float64(4), int64(7), object(4)
memory usage: 77.5+ KB

In [43]:
df.isnull()            #check if there are null values or not

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
656,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
657,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
658,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
659,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [44]:
df.isnull().sum()

Country                     0
League                      0
Club                       34
Player Names                0
Matches_Played              0
Substitution                0
Mins                        0
Goals                       0
xG                          0
xG Per Avg Match            0
Shots                       0
OnTarget                    0
Shots Per Avg Match         0
On Target Per Avg Match     0
Year                        0
dtype: int64

In [45]:
df.describe()

,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
count,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000
mean,22.371212,3.224242,2071.416667,11.810606,10.089606,0.476167,64.177273,28.365152,2.948015,1.315652,2018.363636
std,9.754658,3.839498,900.595049,6.075315,5.724844,0.192831,34.941622,16.363149,0.914906,0.474239,1.367700
min,2.000000,0.000000,264.000000,2.000000,0.710000,0.070000,5.000000,2.000000,0.800000,0.240000,2016.000000
25%,14.000000,0.000000,1363.500000,8.000000,6.100000,0.340000,37.750000,17.000000,2.335000,0.980000,2017.000000
50%,24.000000,2.000000,2245.500000,11.000000,9.285000,0.435000,62.000000,26.000000,2.845000,1.250000,2019.000000
75%,31.000000,5.000000,2822.000000,14.000000,13.252500,0.570000,86.000000,37.000000,3.382500,1.540000,2019.000000
max,38.000000,26.000000,4177.000000,42.000000,32.540000,1.350000,208.000000,102.000000,7.200000,3.630000,2020.000000

In [46]:
de = df.copy()
de

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Netherlands,Eredivisie,(UTR),Gyrano Kerk,24,0,2155,10,7.49,0.33,50,18,2.20,0.79,2020
656,Netherlands,Eredivisie,(AJA),Quincy Promes,18,2,1573,12,9.77,0.59,56,30,3.38,1.81,2020
657,Netherlands,Eredivisie,(PSV),Denzel Dumfries,25,0,2363,7,5.72,0.23,45,14,1.81,0.56,2020
658,Netherlands,Eredivisie,NaN,Cyriel Dessers,26,0,2461,15,14.51,0.56,84,43,3.24,1.66,2020
659,Netherlands,Eredivisie,(PSV),Cody Gakpo,14,11,1557,7,4.43,0.27,38,15,2.32,0.92,2020

In [47]:
#adding a new column
de['Year100'] = de['Year']+100              
de

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year,Year100
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016,2116
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016,2116
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016,2116
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016,2116
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016,2116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Netherlands,Eredivisie,(UTR),Gyrano Kerk,24,0,2155,10,7.49,0.33,50,18,2.20,0.79,2020,2120
656,Netherlands,Eredivisie,(AJA),Quincy Promes,18,2,1573,12,9.77,0.59,56,30,3.38,1.81,2020,2120
657,Netherlands,Eredivisie,(PSV),Denzel Dumfries,25,0,2363,7,5.72,0.23,45,14,1.81,0.56,2020,2120
658,Netherlands,Eredivisie,NaN,Cyriel Dessers,26,0,2461,15,14.51,0.56,84,43,3.24,1.66,2020,2120
659,Netherlands,Eredivisie,(PSV),Cody Gakpo,14,11,1557,7,4.43,0.27,38,15,2.32,0.92,2020,2120

In [48]:
df['Player Names'].value_counts()         #counts the number of times the name occured

Player Names
Andrea Belotti     5
Lionel Messi       5
Luis Suarez        5
Andrej Kramaric    5
Ciro Immobile      5
                  ..
Francois Kamano    1
Lebo Mothiba       1
Gaetan Laborde     1
Falcao             1
Cody Gakpo         1
Name: count, Length: 444, dtype: int64

In [49]:
df['Player Names'].unique()         #name of all unique player

array(['Juanmi Callejon', 'Antoine Griezmann', 'Luis Suarez',
       'Ruben Castro', 'Kevin Gameiro', 'Cristiano Ronaldo',
       'Karim Benzema', 'Neymar ', 'Iago Aspas', 'Sergi Enrich',
       'Aduriz ', 'Sandro Ramlrez', 'Lionel Messi', 'Gerard Moreno',
       'Morata', 'Wissam Ben Yedder', 'Willian Jose', 'Andone ',
       'Cedric Bakambu', 'Isco', 'Mohamed Salah', 'Gregoire Defrel',
       'Ciro Immobile', 'Nikola Kalinic', 'Dries Mertens',
       'Alejandro Gomez', 'Jose CallejOn', 'Iago Falque',
       'Giovanni Simeone', 'Mauro Icardi', 'Diego Falcinelli',
       'Cyril Thereau', 'Edin Dzeko', 'Lorenzo Insigne',
       'Fabio Quagliarella', 'Borriello ', 'Carlos Bacca',
       'Gonzalo Higuain', 'Keita Balde', 'Andrea Belotti', 'Fin Bartels',
       'Lars Stindl', 'Serge Gnabry', 'Wagner ', 'Andrej Kramaric',
       'Florian Niederlechner', 'Robert Lewandowski', 'Emil Forsberg',
       'Timo Werner', 'Nils Petersen', 'Vedad Ibisevic', 'Mario Gomez',
       'Maximilian Philipp', 'A\x81dam Szalai',
       'Pierre-Emerick Aubameyang', 'Guido Burgstaller', 'Max Kruse',
       'Chicharito ', 'Anthony Modeste', 'Arjen Robben', 'Alexis Sanchez',
       'Romelu Lukaku', 'Harry Kane', 'Jamie Vardy', 'Christian Benteke',
       'Pedro None', 'Eden Hazard', 'Roberto Firmino', 'Sadio Mane',
       'Philippe Coutinho', 'Diego Costa', 'Dele Alli', 'Sergio Aguero',
       'Jermain Defoe', 'Fernando Llorente', 'Michail Antonio',
       'Zlatan Ibrahimovic', 'Olivier Giroud', 'Son Heung-Min',
       'Joshua King', 'Diego Souza', 'Pablo ', 'Robinho ', 'Kempes ',
       'Gabriel Jesus', 'Bruno Rangel ', 'Rogerio ', 'Vitor Bueno',
       'Marinho ', 'Grafite ', 'Andres Chavez', 'Cicero Semedo', 'Sassa',
       'Giorgian de Arrascaeta', 'Keno ', 'Fred ', 'Kleber Gladiador',
       'Pottker ', 'Jonathan Copete', 'Ricardo Oliveira',
       'Angel Rodriguez', 'Gareth Bale', 'Rodrigo None', 'Sergio Leon',
       'Maxi Gomez', 'Mikel Oyarzabal', 'Willian Josa', 'Simone Zaza',
       'Portu ', 'Cristhian Stuani', 'Santi Mina', 'Morales ', 'Munir ',
       'Jose Callejon', 'Sergej Milinkovic-Savic', 'Duvan Zapata',
       'Paulo Dybala', 'Mirco Antenucci', 'Luis Alberto',
       'Roberto Inglese', 'Josip Ilicic', 'Ivan Perisic',
       'Leonardo Pavoletti', 'Kevin Lasagna', 'Niclas Fullkrug',
       'Salomon Kalou', 'Thorgan Hazard', 'Jean-Kevin Augustin',
       'Sandro Wagner ', 'Leon Bailey', 'Daniel Didavi',
       'Alfred Finnbogason', 'Davie Selke', 'Mark Uth',
       'Michael Gregoritsch', 'Julian Brandt', 'Kevin Volland', 'Roger ',
       'Arthur Caike', 'Everton ', 'Hernanes ', 'Luiz Fernando',
       'Wellington Paulista', 'Santiago Trellez', 'Jo', 'Thiago Neves',
       'Bruno Henrique', 'Dudu ', 'Diego ', 'Lucca ', 'Henrique Dourado',
       'Andre', 'Edigar Junio ', 'Junior  Dutra', 'Jaime Mata',
       'Inaki Williams', 'Chimy Avila', 'Raul de Tomas', 'Pablo Sarabia',
       'Borja Iglesias', 'Jorge Molina', 'Charles', 'Arkadiusz Milik',
       'Mandzukic None', 'Andrea Petagna', 'Francesco Caputo',
       'Stephan El Shaarawy', 'Gervinho ', 'Krzysztof Piatek',
       'Alassane Plea', 'Kai Havertz', 'Luka Jovic', 'Ante Rebic',
       'Jadon Sancho', 'Ondrej Duda', 'Paco Alcacer', 'Benito Raman',
       'Wout Weghorst', 'Ishak Belfodil', 'Marco Reus',
       'Jean-Philippe Mateta', 'Sebastien Haller', 'Yussuf Poulsen',
       'Angel Di Maria', 'Remi Oudin', 'Nicolas Pepe', 'Emiliano Sala',
       'Jonathan Bamba', "M'Baye Niang", 'Edinson Cavani',
       'Stephane Bahoken', 'Max Gradel', 'Florian Thauvin',
       'Kylian Mbappe-Lottin', 'Wahbi Khazri', 'Falcao ',
       'Gaetan Laborde', 'Andy Delort', 'Moussa Dembele', 'Memphis Depay',
       'Lebo Mothiba', 'Francois Kamano', 'Luka Milivojevic',
       'Paul Pogba', 'Ashley Barnes', 'Glenn Murray', 'Richarlison ',
       'Callum Wilson', 'Gylfi Sigurdsson', 'Raheem Sterling',
       'Ayoze Perez', 'Alexandre Lacazette', 'Raul Jimenez',
       'Lucas Paqueta', 'Juan Cazares', 'Deyverson ', 'Leandro Damiao ',
       'Yago Pikachu', 'Rodrygo ', 'Andres Rios', 'Roger Guedes ',
       'Leandro Pereira ', 'Pedro ', 'Nico Lupez', 'Nene ', 'Gilberto ',
       'Henrique ', 'Willian ', 'Gabriel Barbosa', 'Diego Rossi',
       'Josef Martinez', 'Chris Wondolowski', 'Nani ', 'Kacper Przybylko',
       'Kei Kamara', 'C.J. Sapong', 'Gyasi Zardes', 'Heber ',
       'Mauro Manotas', 'Brian Fernandez', 'Alejandro Pozuelo',
       'Felipe Gutierrez', 'Jordan Morris', 'Raul Ruidiaz',
       'Jozy Altidore', 'Carlos Vela', 'Nemanja Nikolic',
       'Alexandru Mitrita', 'Joselu', 'Carlos Fernandez', 'Ante Budimir',
       'Lucas Perez', 'Loren Moron', 'Raul Garcla', 'Morata ',
       'Sergio Ramos', 'Lucas Ocampos', 'Cazorla ', 'Pote ',
       'Tiquinho Soares', 'Eduardo Mancha', 'Paulinho ', 'Alex Telles',
       'Bruno Viana', 'Mehrdad Mohammadi', 'Carlos Valenzuela',
       'Ruben Lameiras', 'Moussa Marega', 'Gian-Luca Waldschmidt',
       'Samuel Lino', 'Andre Andre', 'Mehdi Taremi', 'Carlos Vinicius',
       'Sergio Oliveira', 'Douglas Tanque', 'Fabio Abreu',
       'Brayan Riascos', 'Alex Telles ', 'Fabio Martins',
       'Haris  Seferovic', 'Joao Teixeira', 'Bruno Fernandes',
       'Angel Gomes', 'Toni MartÃ\xadnez', 'Pizzi ', 'Bozhidar Kraev',
       'Sandro Lima', 'Rodrigo Pinho', 'Thiago Santana', 'Trincao ',
       'Andraz Sporar', 'Ricardo Horta', 'Bruno Duarte', 'Nuno Santos',
       'Domenico Berardi', 'Joao Pedro', 'Andreas Cornelius',
       'Marco Mancosu', 'Lautaro Martrinez', 'Luis Muriel',
       'Gianluca Lapadula', 'Marcus Thuram', 'Rouwen Hennings',
       'Andre Silva', 'Erling Haaland', 'Jhon Cordoba', 'Robin Quaison',
       'Sebastian Andersson', 'Dimitri Payet', 'Kasper Dolberg',
       'Adrien Thomasson', 'Dario Benedetto', 'Ludovic Ajorque',
       'Islam Slimani', 'Adrien Hunou', 'Denis Bouanga',
       'Sehrou Guirassy', 'Ã\x81ngel Di Maria', 'Habib Diallo',
       'Victor Osimhen', 'Dominic Calvert-Lewin', 'Kevin De Bruyne',
       'Chris Wood', 'Anthony Martial', 'Riyad Mahrez', 'Marcus Rashford',
       'Danny Ings', 'Richarlison  ', 'Teemu Pukki', 'Tammy Abraham',
       'Thiago Galhardo', 'Paolo Guerrero', 'Pepe', 'Michael ',
       'Carlos Sanchez', 'Everaldo ', 'Artur ', 'Marcelo  Cirino',
       'Yeferson Soteldo', 'Eduardo Sasha', 'Rafael Moura', 'Antony None',
       'Quincy Promes', 'Dusan Tadic', 'Armando Broja', 'Steven Berghuis',
       'Michael de Leeuw', 'Lois Openda', 'Danilo Nome', 'Lennart Thy',
       'Donyell Malen', 'Noni Madueke', 'Davy Klaassen',
       'Oussama Tannane', 'Vaclav Cerny', 'Vangelis Pavlidis',
       'Henk Veerman', 'Abdou Harroui', 'Rai Vloet', 'Lassina Traore',
       'Georgios Giakoumakis', 'Alex Pozuelo', 'Kevin Molino',
       'Damir Kreilach', 'Bradley Wright-Phillips', 'Nicolas Lodeiro',
       'Daryl Dike', 'Cristian Pavon', 'Chris Mueller', 'Romell Quioto',
       'Gustavo Bou', 'Robert Beric', 'Ayo Akinola', 'Jeremy Ebobisse',
       'Diego Valeri', 'Youssef   En-Nesyri', 'Carlos Soler',
       'Cristian Tello', 'Esteban Burgos', 'Joao Felix',
       'Federico Valverde', 'Kike GarcIa', 'Ansu Fati', 'Roberto Soriano',
       'Gaetano Castrovilli', 'Henrikh Mkhitaryan', 'Jordan Veretout',
       'Lautaro MartInez', 'Hirving Lozano', 'Lucas Alario', 'Bas Dost',
       'Dani Olmo', 'Ellyes Skhiri', 'Thomas Muller', 'Andre Hahn',
       'Daniel Caligiuri', 'Matheus Cunha', 'Ludovic Blas', 'Karl Toko',
       'Burak Yilmaz', 'Ibrahima Niane', 'Boulaye Dia', 'Moise Kean',
       'Ignatius Ganago', 'Irvin Cardona', 'Wissam Ben', 'Amine Gouiri',
       'Mama Balde', 'Gael Kakuta', 'James Ward-Prowse', 'Diogo Jota',
       'Wilfried Zaha', 'Jack Grealish', 'Jarrod Bowen',
       'Patrick Bamford', 'Danny Ings ', 'Neal Maupay', 'Ollie Watkins',
       'Luciano ', 'Vinicius ', 'Raphael Veiga', 'Luiz Adriano',
       'Cleber ', 'German Cano', 'Brenner None', 'Matheus Babi',
       'Alerrandro ', 'Claudinho ', 'Robson', 'Renato Kayzer',
       'Donny van de Beek', 'Teun Koopmeiners', 'Cantalapiedra ',
       'Bryan Linssen', 'Matavz ', 'Oussama Idrissi', 'Chidera Ejuke',
       'Myron Boadu', 'Klaas-Jan Huntelaar', 'Haris Vuckic',
       'Gyrano Kerk', 'Denzel Dumfries', 'Cyriel Dessers ', 'Cody Gakpo'],
      dtype=object)

In [50]:
df['Player Names'].unique()

array(['Juanmi Callejon', 'Antoine Griezmann', 'Luis Suarez',
       'Ruben Castro', 'Kevin Gameiro', 'Cristiano Ronaldo',
       'Karim Benzema', 'Neymar ', 'Iago Aspas', 'Sergi Enrich',
       'Aduriz ', 'Sandro Ramlrez', 'Lionel Messi', 'Gerard Moreno',
       'Morata', 'Wissam Ben Yedder', 'Willian Jose', 'Andone ',
       'Cedric Bakambu', 'Isco', 'Mohamed Salah', 'Gregoire Defrel',
       'Ciro Immobile', 'Nikola Kalinic', 'Dries Mertens',
       'Alejandro Gomez', 'Jose CallejOn', 'Iago Falque',
       'Giovanni Simeone', 'Mauro Icardi', 'Diego Falcinelli',
       'Cyril Thereau', 'Edin Dzeko', 'Lorenzo Insigne',
       'Fabio Quagliarella', 'Borriello ', 'Carlos Bacca',
       'Gonzalo Higuain', 'Keita Balde', 'Andrea Belotti', 'Fin Bartels',
       'Lars Stindl', 'Serge Gnabry', 'Wagner ', 'Andrej Kramaric',
       'Florian Niederlechner', 'Robert Lewandowski', 'Emil Forsberg',
       'Timo Werner', 'Nils Petersen', 'Vedad Ibisevic', 'Mario Gomez',
       'Maximilian Philipp', 'A\x81dam Szalai',
       'Pierre-Emerick Aubameyang', 'Guido Burgstaller', 'Max Kruse',
       'Chicharito ', 'Anthony Modeste', 'Arjen Robben', 'Alexis Sanchez',
       'Romelu Lukaku', 'Harry Kane', 'Jamie Vardy', 'Christian Benteke',
       'Pedro None', 'Eden Hazard', 'Roberto Firmino', 'Sadio Mane',
       'Philippe Coutinho', 'Diego Costa', 'Dele Alli', 'Sergio Aguero',
       'Jermain Defoe', 'Fernando Llorente', 'Michail Antonio',
       'Zlatan Ibrahimovic', 'Olivier Giroud', 'Son Heung-Min',
       'Joshua King', 'Diego Souza', 'Pablo ', 'Robinho ', 'Kempes ',
       'Gabriel Jesus', 'Bruno Rangel ', 'Rogerio ', 'Vitor Bueno',
       'Marinho ', 'Grafite ', 'Andres Chavez', 'Cicero Semedo', 'Sassa',
       'Giorgian de Arrascaeta', 'Keno ', 'Fred ', 'Kleber Gladiador',
       'Pottker ', 'Jonathan Copete', 'Ricardo Oliveira',
       'Angel Rodriguez', 'Gareth Bale', 'Rodrigo None', 'Sergio Leon',
       'Maxi Gomez', 'Mikel Oyarzabal', 'Willian Josa', 'Simone Zaza',
       'Portu ', 'Cristhian Stuani', 'Santi Mina', 'Morales ', 'Munir ',
       'Jose Callejon', 'Sergej Milinkovic-Savic', 'Duvan Zapata',
       'Paulo Dybala', 'Mirco Antenucci', 'Luis Alberto',
       'Roberto Inglese', 'Josip Ilicic', 'Ivan Perisic',
       'Leonardo Pavoletti', 'Kevin Lasagna', 'Niclas Fullkrug',
       'Salomon Kalou', 'Thorgan Hazard', 'Jean-Kevin Augustin',
       'Sandro Wagner ', 'Leon Bailey', 'Daniel Didavi',
       'Alfred Finnbogason', 'Davie Selke', 'Mark Uth',
       'Michael Gregoritsch', 'Julian Brandt', 'Kevin Volland', 'Roger ',
       'Arthur Caike', 'Everton ', 'Hernanes ', 'Luiz Fernando',
       'Wellington Paulista', 'Santiago Trellez', 'Jo', 'Thiago Neves',
       'Bruno Henrique', 'Dudu ', 'Diego ', 'Lucca ', 'Henrique Dourado',
       'Andre', 'Edigar Junio ', 'Junior  Dutra', 'Jaime Mata',
       'Inaki Williams', 'Chimy Avila', 'Raul de Tomas', 'Pablo Sarabia',
       'Borja Iglesias', 'Jorge Molina', 'Charles', 'Arkadiusz Milik',
       'Mandzukic None', 'Andrea Petagna', 'Francesco Caputo',
       'Stephan El Shaarawy', 'Gervinho ', 'Krzysztof Piatek',
       'Alassane Plea', 'Kai Havertz', 'Luka Jovic', 'Ante Rebic',
       'Jadon Sancho', 'Ondrej Duda', 'Paco Alcacer', 'Benito Raman',
       'Wout Weghorst', 'Ishak Belfodil', 'Marco Reus',
       'Jean-Philippe Mateta', 'Sebastien Haller', 'Yussuf Poulsen',
       'Angel Di Maria', 'Remi Oudin', 'Nicolas Pepe', 'Emiliano Sala',
       'Jonathan Bamba', "M'Baye Niang", 'Edinson Cavani',
       'Stephane Bahoken', 'Max Gradel', 'Florian Thauvin',
       'Kylian Mbappe-Lottin', 'Wahbi Khazri', 'Falcao ',
       'Gaetan Laborde', 'Andy Delort', 'Moussa Dembele', 'Memphis Depay',
       'Lebo Mothiba', 'Francois Kamano', 'Luka Milivojevic',
       'Paul Pogba', 'Ashley Barnes', 'Glenn Murray', 'Richarlison ',
       'Callum Wilson', 'Gylfi Sigurdsson', 'Raheem Sterling',
       'Ayoze Perez', 'Alexandre Lacazette', 'Raul Jimenez',
       'Lucas Paqueta', 'Juan Cazares', 'Deyverson ', 'Leandro Damiao ',
       'Yago Pikachu', 'Rodrygo ', 'Andres Rios', 'Roger Guedes ',
       'Leandro Pereira ', 'Pedro ', 'Nico Lupez', 'Nene ', 'Gilberto ',
       'Henrique ', 'Willian ', 'Gabriel Barbosa', 'Diego Rossi',
       'Josef Martinez', 'Chris Wondolowski', 'Nani ', 'Kacper Przybylko',
       'Kei Kamara', 'C.J. Sapong', 'Gyasi Zardes', 'Heber ',
       'Mauro Manotas', 'Brian Fernandez', 'Alejandro Pozuelo',
       'Felipe Gutierrez', 'Jordan Morris', 'Raul Ruidiaz',
       'Jozy Altidore', 'Carlos Vela', 'Nemanja Nikolic',
       'Alexandru Mitrita', 'Joselu', 'Carlos Fernandez', 'Ante Budimir',
       'Lucas Perez', 'Loren Moron', 'Raul Garcla', 'Morata ',
       'Sergio Ramos', 'Lucas Ocampos', 'Cazorla ', 'Pote ',
       'Tiquinho Soares', 'Eduardo Mancha', 'Paulinho ', 'Alex Telles',
       'Bruno Viana', 'Mehrdad Mohammadi', 'Carlos Valenzuela',
       'Ruben Lameiras', 'Moussa Marega', 'Gian-Luca Waldschmidt',
       'Samuel Lino', 'Andre Andre', 'Mehdi Taremi', 'Carlos Vinicius',
       'Sergio Oliveira', 'Douglas Tanque', 'Fabio Abreu',
       'Brayan Riascos', 'Alex Telles ', 'Fabio Martins',
       'Haris  Seferovic', 'Joao Teixeira', 'Bruno Fernandes',
       'Angel Gomes', 'Toni MartÃ\xadnez', 'Pizzi ', 'Bozhidar Kraev',
       'Sandro Lima', 'Rodrigo Pinho', 'Thiago Santana', 'Trincao ',
       'Andraz Sporar', 'Ricardo Horta', 'Bruno Duarte', 'Nuno Santos',
       'Domenico Berardi', 'Joao Pedro', 'Andreas Cornelius',
       'Marco Mancosu', 'Lautaro Martrinez', 'Luis Muriel',
       'Gianluca Lapadula', 'Marcus Thuram', 'Rouwen Hennings',
       'Andre Silva', 'Erling Haaland', 'Jhon Cordoba', 'Robin Quaison',
       'Sebastian Andersson', 'Dimitri Payet', 'Kasper Dolberg',
       'Adrien Thomasson', 'Dario Benedetto', 'Ludovic Ajorque',
       'Islam Slimani', 'Adrien Hunou', 'Denis Bouanga',
       'Sehrou Guirassy', 'Ã\x81ngel Di Maria', 'Habib Diallo',
       'Victor Osimhen', 'Dominic Calvert-Lewin', 'Kevin De Bruyne',
       'Chris Wood', 'Anthony Martial', 'Riyad Mahrez', 'Marcus Rashford',
       'Danny Ings', 'Richarlison  ', 'Teemu Pukki', 'Tammy Abraham',
       'Thiago Galhardo', 'Paolo Guerrero', 'Pepe', 'Michael ',
       'Carlos Sanchez', 'Everaldo ', 'Artur ', 'Marcelo  Cirino',
       'Yeferson Soteldo', 'Eduardo Sasha', 'Rafael Moura', 'Antony None',
       'Quincy Promes', 'Dusan Tadic', 'Armando Broja', 'Steven Berghuis',
       'Michael de Leeuw', 'Lois Openda', 'Danilo Nome', 'Lennart Thy',
       'Donyell Malen', 'Noni Madueke', 'Davy Klaassen',
       'Oussama Tannane', 'Vaclav Cerny', 'Vangelis Pavlidis',
       'Henk Veerman', 'Abdou Harroui', 'Rai Vloet', 'Lassina Traore',
       'Georgios Giakoumakis', 'Alex Pozuelo', 'Kevin Molino',
       'Damir Kreilach', 'Bradley Wright-Phillips', 'Nicolas Lodeiro',
       'Daryl Dike', 'Cristian Pavon', 'Chris Mueller', 'Romell Quioto',
       'Gustavo Bou', 'Robert Beric', 'Ayo Akinola', 'Jeremy Ebobisse',
       'Diego Valeri', 'Youssef   En-Nesyri', 'Carlos Soler',
       'Cristian Tello', 'Esteban Burgos', 'Joao Felix',
       'Federico Valverde', 'Kike GarcIa', 'Ansu Fati', 'Roberto Soriano',
       'Gaetano Castrovilli', 'Henrikh Mkhitaryan', 'Jordan Veretout',
       'Lautaro MartInez', 'Hirving Lozano', 'Lucas Alario', 'Bas Dost',
       'Dani Olmo', 'Ellyes Skhiri', 'Thomas Muller', 'Andre Hahn',
       'Daniel Caligiuri', 'Matheus Cunha', 'Ludovic Blas', 'Karl Toko',
       'Burak Yilmaz', 'Ibrahima Niane', 'Boulaye Dia', 'Moise Kean',
       'Ignatius Ganago', 'Irvin Cardona', 'Wissam Ben', 'Amine Gouiri',
       'Mama Balde', 'Gael Kakuta', 'James Ward-Prowse', 'Diogo Jota',
       'Wilfried Zaha', 'Jack Grealish', 'Jarrod Bowen',
       'Patrick Bamford', 'Danny Ings ', 'Neal Maupay', 'Ollie Watkins',
       'Luciano ', 'Vinicius ', 'Raphael Veiga', 'Luiz Adriano',
       'Cleber ', 'German Cano', 'Brenner None', 'Matheus Babi',
       'Alerrandro ', 'Claudinho ', 'Robson', 'Renato Kayzer',
       'Donny van de Beek', 'Teun Koopmeiners', 'Cantalapiedra ',
       'Bryan Linssen', 'Matavz ', 'Oussama Idrissi', 'Chidera Ejuke',
       'Myron Boadu', 'Klaas-Jan Huntelaar', 'Haris Vuckic',
       'Gyrano Kerk', 'Denzel Dumfries', 'Cyriel Dessers ', 'Cody Gakpo'],
      dtype=object)

In [51]:
link = 'https://raw.githubusercontent.com/AshishJangra27/Data-Analysis-with-Python-GFG/main/3.%20Data%20Preprocessing%20-%20Removing%20Null%20Value%20Rows/googleplaystore.csv'

df = pd.read_csv(link)
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [52]:
df.isnull().sum()
print(len(df))

10841

In [53]:
#from above we can see that there are null values in rating,type,content rating, current ver, android ver
df.dropna(inplace=True,axis=0)
#This will delete all the null values row wise

In [54]:
df.dropna(inplace=True,axis=1)
#This will delete all the null values column wise

In [55]:
df.head()
print(len(df))

9360

In [56]:
link = 'https://raw.githubusercontent.com/AshishJangra27/Data-Analysis-with-Python-GFG/main/3.%20Data%20Preprocessing%20-%20Removing%20Null%20Value%20Rows/googleplaystore.csv'

df = pd.read_csv(link)

print(len(df))
df

10841

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [60]:
#now if we don't want to delete the null values we want to fill those values by some other values
#for integer values
missing_values = round(df['Rating'].mean(),2)            #this will fill the null values with the mean of average column
df['Rating'] = df['Rating'].fillna(missing_values)
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64

In [61]:
#for categorical values
df['Current Ver'] = df['Current Ver'].fillna('Varies on Device')

In [62]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       0
Android Ver       3
dtype: int64

In [63]:
df.sample(5)    #give 5 random sample output

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
7874,CT Head Basic Interpretation,FAMILY,4.19,1,16M,100+,Free,0,Everyone,Education,"June 11, 2018",1.0.1,4.0 and up
6726,COMSATS BOOK STORE FOR BS(CS),FAMILY,5.00,15,94M,50+,Free,0,Everyone,Education,"July 11, 2018",2.0,4.0.3 and up
3877,Akinator,FAMILY,4.30,1805398,55M,"50,000,000+",Free,0,Teen,Entertainment,"June 11, 2018",6.5.2,4.4 and up
7826,CS Interview FAQs,FAMILY,4.30,99,1.1M,"10,000+",Free,0,Everyone,Education,"February 11, 2013",1.13,2.2 and up
2574,MobilePatrol Public Safety App,SOCIAL,4.00,22695,Varies with device,"1,000,000+",Free,0,Everyone 10+,Social,"June 21, 2018",Varies with device,Varies with device

In [66]:
#to create CSV
data = { 'one'   : pd.Series([1, 2, 3, 4]),
         'two'   : pd.Series([10, 20, 30, 40]),
         'three' : pd.Series([100, 200, 300, 400]),
         'four'  : pd.Series([1000, 2000, 3000, 4000])}

df = pd.DataFrame(data)
df.to_csv("Number.csv")

In [67]:
df.to_csv("Numbers.csv", index=False)